//
// Created by pkua on 08.06.22.
//

#ifndef RAMPACK_LAYERWISECELLOPTIMIZATIONTRANSFORMER_H
#define RAMPACK_LAYERWISECELLOPTIMIZATIONTRANSFORMER_H


class LayerWiseCellOptimizationTransformer {

};


#endif //RAMPACK_LAYERWISECELLOPTIMIZATIONTRANSFORMER_H
